### ISSUE TITLE
Dumb question— where to put the mod files?

### ISSUE THREAD

**Issue by zachmayer** [Xarun/ForScienceContinued#4]

**Comment by Xarun** [comment]
The zip files are all structured so that you only have to extract them into your kerbal folder and merge the folder. 

See [here](http://forum.kerbalspaceprogram.com/threads/106004-1-0-2-ForScienceContinued-V1-0-3-23-05-2015?p=1936015&viewfull=1#post1936015)

**Comment by zachmayer** [comment]
Thank you!  Sorry to ask a silly question.
