### ISSUE TITLE
DMagic changed manufacturer name

### ISSUE THREAD

**Issue by CrawdadCletis** [Xarun/ForScienceContinued#5]
The code identifies DMagic experiments by looking for parts where the manufacturer is "DMagic Orbital Science".  DMagic recently changed the manufacturer name on all the parts to just "DMagic".

https://github.com/DMagic1/Orbital-Science/commit/09b4cac458477b8200ada22b0b2403b9bcaf3cf9

**Comment by Xarun** [comment]
Fixed with the new release
